### PR TITLE
Multiple characteristics feature #175

### PR DESCRIPTION
**Pull request by chegewara**

### CODE REVIEW

**Comment by rweller59** [comment]
Having issue with multiple characteristics and 1 service. Communications working fine with 1 characteristic and confirmed with nRF Connect app. Added second characteristic (same and different uuid) and nRF Connect cannot find any characteristics. Using ESPIDF.

Looked like this has been addressed. Is the fix not in the current code files? Or am I discovering something new.
Here is the code - when one of the characteristics is commented out, everything seems to work fine

#define SERVICE_UUID 				"bbfd0423-0869-4a22-b734-ddac4cc3ffab"
#define CONFIG_CHARACTERISTIC_UUID 	"ac65ebd8-72ec-4fd2-a964-b12dda6956e1"
#define DATA_CHARACTERISTIC_UUID	"97d085cb-84af-4f8e-80c3-2ca99089a4fa"
// Characteristics and descriptors

BLECharacteristic *configCharacteristic;
BLECharacteristic *dataCharacteristic;
/ process BLE connections
class bleServerCallback: public BLEServerCallbacks {
	void onConnect(BLEServer* pServer) {
		ESP_LOGI(LOG, "Bluetooth client connected");
		ble_connected = true;
		}
	void onDisconnect(BLEServer* pServer) {
		ESP_LOGI(LOG, "Bluetooth client disconnected");
		ble_connected = false;
		pServer->getAdvertising()->start();
		}
};

// process external characteristic calls
class bleCharacteristicCallback: public BLECharacteristicCallbacks {
	void onWrite(BLECharacteristic* pCharacteristic) {
		ESP_LOGI(LOG, "onWrite");
		}

	void onRead(BLECharacteristic* pCharacteristic) {
		ESP_LOGE(LOG, "client read characteristic");
		}
};


// create BLE server, services and characteristics
void init(void) {
	BLEDevice::init("ESP32");
	BLEServer *pServer = BLEDevice::createServer();
	pServer->setCallbacks(new bleServerCallback());
	BLEService *pService = pServer->createService(BLEUUID(SERVICE_UUID),20);
/*
	// characteristic for configuration with callback defined
	configCharacteristic = pService->createCharacteristic(
		BLEUUID(CONFIG_CHARACTERISTIC_UUID),
		BLECharacteristic::PROPERTY_READ   |
		BLECharacteristic::PROPERTY_WRITE  |
		BLECharacteristic::PROPERTY_NOTIFY |
		BLECharacteristic::PROPERTY_INDICATE
	);
	configCharacteristic->addDescriptor(new BLE2902());
	configCharacteristic->setCallbacks(new bleCharacteristicCallback());


	dataCharacteristic = pService->createCharacteristic(
		BLEUUID(DATA_CHARACTERISTIC_UUID),
		BLECharacteristic::PROPERTY_READ   |
		BLECharacteristic::PROPERTY_WRITE  |
		BLECharacteristic::PROPERTY_NOTIFY |
		BLECharacteristic::PROPERTY_INDICATE
	);
	dataCharacteristic->addDescriptor(new BLE2902());

	pService->start();
	pServer->getAdvertising()->start();
}

**Comment by chegewara** [comment]
Multiple characteristics feature is about few characteristics with the same UUID connected with one service. Your issue is different, but still needs to be checked.

**Comment by rweller59** [comment]
should i move it to another issue?

**Comment by chegewara** [comment]
Sample server with 2 characteristics works, then its something with your code most likely. But to be clear, i am using latest esp-idf, latest toolchain and latest esp32-snippets, all git pull today.

**Comment by rweller59** [comment]
ok. I'm 3-4 weeks old on everything but snippets (which I got today). I'll get new everything and try again.

Code seems pretty simple - either characteristic works fine by itself, just not together.

**Comment by chegewara** [comment]
To be honest, i did run SampleWrite today and i cant see any service, and this is very simple example. So we have to review all examples and see what is wrong. In mean time you can try this example which is working to me:

```
/**
 * Create a new BLE server.
 */
#include "BLEDevice.h"
#include "BLEServer.h"
#include "BLEUtils.h"
#include "BLE2902.h"
#include <esp_log.h>
#include <string>
#include <Task.h>


#include "sdkconfig.h"

static char LOG_TAG[] = "SampleServer";

class MainBLEServer: public Task {
	void run(void *data) {
		ESP_LOGD(LOG_TAG, "Starting BLE work!");

		BLEDevice::init("ESP32");
		BLEServer* pServer = BLEDevice::createServer();

		BLEService* pService = pServer->createService("91bad492-b950-4226-aa2b-4ede9fa42f59");

		BLECharacteristic* pCharacteristic = pService->createCharacteristic(
				BLEUUID("0d563a58-196a-48ce-ace2-dfec78acc814"),
				BLECharacteristic::PROPERTY_BROADCAST | BLECharacteristic::PROPERTY_READ  |
				BLECharacteristic::PROPERTY_NOTIFY    | BLECharacteristic::PROPERTY_WRITE |
				BLECharacteristic::PROPERTY_INDICATE
			);

		pCharacteristic = pService->createCharacteristic(
					BLEUUID("0d563a58-196a-48ce-ace2-dfec78acc815"),
					BLECharacteristic::PROPERTY_BROADCAST | BLECharacteristic::PROPERTY_READ  |
					BLECharacteristic::PROPERTY_NOTIFY    | BLECharacteristic::PROPERTY_WRITE |
					BLECharacteristic::PROPERTY_INDICATE
				);

		pCharacteristic->setValue("Hello World!");

		BLE2902* p2902Descriptor = new BLE2902();
		p2902Descriptor->setNotifications(true);
		pCharacteristic->addDescriptor(p2902Descriptor);

		pService->start();

		BLEAdvertising* pAdvertising = pServer->getAdvertising();
		pAdvertising->addServiceUUID(BLEUUID(pService->getUUID()));
		pAdvertising->start();

		ESP_LOGD(LOG_TAG, "Advertising started!");
		delay(1000000);
	}
};


void SampleServer(void)
{
	//esp_log_level_set("*", ESP_LOG_DEBUG);
	MainBLEServer* pMainBleServer = new MainBLEServer();
	pMainBleServer->setStackSize(20000);
	pMainBleServer->start();

} // app_main

```

**Comment by chegewara** [comment]
Can you change this line:
`BLEService pService = pServer->createService(BLEUUID(SERVICE_UUID),20);`
with this code:
`BLEService pService = pServer->createService(SERVICE_UUID);`

**Comment by rweller59** [comment]
can't compile at the moment after getting latest release of espidf (No rule to make target errors). Trying to figure that out then I'll give this a try.

I didn't have the '20' in there previously (didn't have any number) and still had the problem. Seems like if I was creating the service wrong, nothing would work?

**Comment by chegewara** [comment]
Its not about '20', but about `BLEUUID`.

About `No rule to make target errors`, try to `make clean` and delete build folder.

**Comment by rweller59** [comment]
yes, I assumed that was the higher potential issue. 
did clean and build. didn't delete build folder, just tried that but still can't build.

**Comment by rweller59** [comment]
maybe I have a toolchain issue. did you have to update toolchain for latest release? if so, is there a documented process you could direct me to?

**Comment by chegewara** [comment]
http://esp-idf.readthedocs.io/en/latest/get-started/index.html#setup-toolchain

**Comment by rweller59** [comment]
yeh, on that page now. wasn't sure how up-to-date they are keeping the links

**Comment by rweller59** [comment]
can't seem to find a solution to this build error. any other suggestions

**Comment by chegewara** [comment]
check if you can compile without errors regular esp-idf hello-world example

**Comment by rweller59** [comment]
stupid error. renamed old version of cpp_utils folder but left it in components directory

**Comment by rweller59** [comment]
also, after changing to BLEService pService = pServer->createService(SERVICE_UUID); both characteristics are recognized by nRF - wonder why it worked the other way with 1 characteristic.

I noticed in your test code above that you only added 1 BLE2902 descriptor and I am adding one for each characteristic. Is adding one for multiple characteristics the right way to define?

**Comment by chegewara** [comment]
You have to understand that both commands are good and should have work:
```
BLEService pService = pServer->createService(BLEUUID(SERVICE_UUID),20);
BLEService pService = pServer->createService(SERVICE_UUID);
```

No, you need BLE2902 descriptor for each characteristic that is serving notify and/or indicate.

**Pull request merged**
