### PR TITLE
Revert "Release memory from CLASSIC_BT when not enabled"

### PR DESCRIPTION
**Pull request by chegewara**
Reverts nkolban/esp32-snippets#696

Causes #705

### CODE REVIEW

**Comment by czuvich** [comment]
Is esp_bt_controller_mem_release for classic BT a problem with BLEDevice::init or with IDF?  I just found out about this method, and it’s be great to be able to use it.

I tried invoking it directly before BLEDevice::init, but BLEScan doesn’t work.

**Comment by chegewara** [comment]
There is no issue with `esp_bt_controller_mem_release` beside it needs to be called before controller_init. There was issue with `esp_bt_controller_enable` that was omitted and causing `BT_LOG: Conroller not initialised` error.

**Comment by czuvich** [comment]
Thanks for the quick reply!  I saw that the esp_bt_controller_mem_release call was commented out with a FIXME.  Is esp_bt_controller_mem_release something the developer needs to call or will it be implemented by BLEDevice?

**Comment by chegewara** [comment]
It was commented out because at the time i was not very experienced and it was left out for so long because it was not very important too. Now i know more and i changes it in this code:
https://github.com/nkolban/esp32-snippets/blob/features/cpp_utils/BLEDevice.cpp#L350-L373

**Comment by chegewara** [comment]
You can always call `esp_bt_controller_mem_release ` before BLEDevice::init() and it will do the job.

**Comment by czuvich** [comment]
Thanks for that quick fix!  Amazing work on this library too!

**Comment by chegewara** [comment]
This issue ive got some time ago calling release_mem 
https://github.com/espressif/arduino-esp32/issues/1594

**Comment by czuvich** [comment]
Got it.  I'll bug the IDF team :)  Thanks!

**Pull request merged**
