### PR TITLE
IBeacon fix #196

### LINKED ISSUE #196: Provide raw data settings for advertising and scan response
BLE ibeacon requires to advertise raw data and such it requires to add this functionality(optionaly) to resolve issue #195.

### PR DESCRIPTION
**Pull request by chegewara**
#196

### CODE REVIEW

**Comment by qrpfun** [comment]
I had BLEAdvertising.* updated with the latest fix but still something wrong in my understanding because I can't see any beacon data structure from raw datas.
Is these iBeacon's examples datas correctly created after service start ?

```
  pService->start();
  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  
  Serial.println("Building up iBeacon advertising ..");
  BLEBeacon myBeacon;
  // Setting up according to https://os.mbed.com/blog/entry/BLE-Beacons-URIBeacon-AltBeacons-iBeacon/
  myBeacon.setManufacturerId(uint16_t (0x1AFF));
  myBeacon.setMajor(uint16_t (0x1234));
  myBeacon.setMinor(uint16_t (0x5678));
  myBeacon.setProximityUUID(BLEUUID((uint32_t)0x11223344));
  myBeacon.setSignalPower(uint8_t (0xC8));
  BLEAdvertisementData advertisementData;
  advertisementData.setFlags(ESP_BLE_ADV_FLAG_LIMIT_DISC | ESP_BLE_ADV_FLAG_GEN_DISC | ESP_BLE_ADV_FLAG_BREDR_NOT_SPT);
  // Build the iBeacon data structure and store it in std::string beaconData
  advertisementData.setManufacturerData(myBeacon.getData());
  pAdvertising->setAdvertisementData(advertisementData);
  pAdvertising->start();

```
and this what nRF connect sees on raw data field:
foto 19-12-17 19 03 41

thanks in advance

**Comment by chegewara** [comment]
In your advertising data for some reason we are missing this `advertisementData.setFlags(ESP_BLE_ADV_FLAG_LIMIT_DISC | ESP_BLE_ADV_FLAG_GEN_DISC | ESP_BLE_ADV_FLAG_BREDR_NOT_SPT);`

Try with my test app:
https://github.com/chegewara/esp32-tests-library/tree/master/ibeacon_test

**Comment by qrpfun** [comment]
May be some other snippet to be updated ? but which one ... really no idea.
I have seen your test app and changed code according to that, but still not right
Here is the new code (seem exactly the same) and the raw data in the image:

```
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

const BLEUUID MY_UUID = BLEUUID("26410a28-2a4c-4d57-ae2f-67a4d96b1f83");

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");

  BLEDevice::init("MyESP32");
  BLEServer *pServer = BLEDevice::createServer();
  
  BLEBeacon myBeacon;
  myBeacon.setManufacturerId(uint16_t (0x1AFF));
  myBeacon.setMajor(uint16_t (0x1234));
  myBeacon.setMinor(uint16_t (0x5678));
  myBeacon.setProximityUUID(MY_UUID);
  myBeacon.setSignalPower(uint8_t (0xC8));
  BLEAdvertisementData advertisementData;
  advertisementData.setFlags(ESP_BLE_ADV_FLAG_LIMIT_DISC | ESP_BLE_ADV_FLAG_GEN_DISC | ESP_BLE_ADV_FLAG_BREDR_NOT_SPT);
  advertisementData.setManufacturerData(myBeacon.getData());

  BLEAdvertising* pAdvertising = pServer->getAdvertising();
  pAdvertising->setAdvertisementData(advertisementData);
  pAdvertising->setScanResponseData(advertisementData);
  pAdvertising->start();
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(2000);
}
```

foto 19-12-17 19 49 18

**Comment by chegewara** [comment]
Now i see. You are trying to use it in arduino-ide. Let me do some tests.

**Comment by chegewara** [comment]
Im not sure where is the problem. This is what i did:
- copy BLEAdverising.* and BLEAdvertisedDevice.* from https://github.com/nkolban/esp32-snippets to your Arduino BLE library
- fix any missing dependices
- works

* Dont use full https://github.com/nkolban/esp32-snippets library in arduino-ide because it will cause massive issues because of c++ exceptions. We have to wait until ESP32-Arduino library will be updated

**Comment by qrpfun** [comment]
ok it was what I did but resulting data are those in the snapshot above.
they are not viewed as beacon data.
Did you used my code above and you have same results or something else ?
Did you used nRF  connect on android or iPhone ? (mine is on iPhone)

**Comment by chegewara** [comment]
Yes, im using your code to test arduino-ide and im using android nRF connect to test. Because you have custom manufacturer i can see it as a Beacon not iBeacon but im guessing this is what you are expecting.
screenshot-1513719324054

**Comment by qrpfun** [comment]
I'm getting confused about the content I want to have at the end.
Now I have removed manufacturer so it remains the default inside the libs (0x4C00) and this il the resulting content. It seems to be a good iBeacon and the same as yours.
Now I have to understand it's usage with the phone

foto 19-12-17 23 37 56

**Comment by chegewara** [comment]
And now what you are missing is `0x020106` which should be set by this command `advertisementData.setFlags(ESP_BLE_ADV_FLAG_GEN_DISC | ESP_BLE_ADV_FLAG_BREDR_NOT_SPT);`

**Comment by chegewara** [comment]
@qrpfun Maybe just delete BLE library and download fresh from library, then add or change files i mentioned before?

**Comment by qrpfun** [comment]
mhh BLE lib should be clean. I had downloaded recently. I see the setFlags works inside BLEAdvertising.cpp as the setManufacturerData ... may the first fails or the second overwrites ... missing flags are really painful at this time .. I give up and will get back tomorrow evening looking better inside libs. Anyway you say your ones are working right under arduino IDE .. give up now

**Pull request merged**
