### PR TITLE
Added arduino security examples

### PR DESCRIPTION
**Pull request by chegewara**
As for now those examples will work only with modified library since we still are waiting for new arduino-esp32 commit with c++ exceptions included. ESP32Arduino.zip is added, but its only to excercise with new features. 

[ESP32_BLE.zip](https://github.com/nkolban/esp32-snippets/files/1584439/ESP32_BLE.zip)

### CODE REVIEW

**Comment by chegewara** [comment]
#302 addressed

**Comment by felixzhang97** [comment]
Hello, i am referring to BLE_server_passkey.ino.
Can you help me how to set hardcoded passkey instead of randomly generated one?
Thanks before

**Comment by chegewara** [comment]
I have no idea if its possible, because all passkeys are generated by bluedroid stack. I will have to ask devs.

**Comment by felixzhang97** [comment]
Hello, do you have any update?

**Comment by chegewara** [comment]
@felixzhang97 
https://github.com/nkolban/esp32-snippets/tree/master/cpp_utils/tests/BLETests/security

**Comment by chegewara** [comment]
@felixzhang97 
If you are asking about hardcoded passkey then we are waiting, it has been promised but not implemented yet

**Comment by felixzhang97** [comment]
@chegewara alright then, thankyou
glad to see progress on the development

**Comment by RottenVanSuti** [comment]
Hello @chegewara  What do you mean by  modified library? Are the changes in code that you did in #293 ?

**Comment by chegewara** [comment]
I remember now, there was time when security was not implemented in arduino because arduino library for some time was not updated on github. So i decided to export zip library like is described here since some arduino users dont have option to do it:

https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md

But this post is outdated now.

**Comment by chegewara** [comment]
Yes, and if for some reason you have any problems please open issue and i will try to help.

**Comment by RottenVanSuti** [comment]
Ok, I´ll give it a try, thanks a lot @chegewara

**Comment by skyng22003** [comment]
Thanks for providing the examples @chegewara 

Hi I have the most recent version of ESP32_BLE and get a compile error 

 'LOG_TAG' was not declared in this scope
esp_log_buffer_hex(LOG_TAG, auth_cmpl.bd_addr, sizeof(auth_cmpl.bd_addr));

Has the security features not been implemented in the main library?

**Comment by chegewara** [comment]
In which file you have this error? You can find this line and change `LOG_TAG` with some string.

**Comment by skyng22003** [comment]
Thanks for the quick reply, it's in the BLE_client_numeric_confirmation.ino and BLE_client_passkey.ino
Do you mean #define?

**Comment by skyng22003** [comment]
If I comment out esp_log_buffer_hex(LOG_TAG, auth_cmpl.bd_addr, sizeof(auth_cmpl.bd_addr)); 
this line everything compiles fine but the program crashes when it connects to the BLE_Server

**Comment by chegewara** [comment]
Could you open new issue and provide logs when it crash? Also ty to use this tool:
https://github.com/me-no-dev/EspExceptionDecoder

**Pull request merged**
